const A=document.getElementById('app'), T=document.getElementById('title'), toastEl=document.getElementById('toast');
const KEY='foxos_v08';
const defaults={name:'FOX OS Sandbox',owner:'Foxbin',version:'0.8.0',target:'BONELAB',files:{'Main.cs':'using BoneLib;\n\nnamespace FOXOS {\n    public class Main {\n        public void Start() {\n            // FOX OS entry point\n        }\n    }\n}\n'}};
const base={project:structuredClone(defaults),view:'home',file:'Main.cs',builds:[],history:[],bookmarks:['https://github.com/foxbin8766-oss/FoxOSC'],settings:{accent:'#0796e6',compact:false,animations:true,wallpaper:'grid',density:'comfortable',rounded:true},memory:[],tasks:[],notifications:[],permissions:{memory:false,devices:false,network:false,files:false,agents:false},devices:[{name:'Chromebook',type:'Host',status:'Online',trust:'Trusted'},{name:'Quest Simulator',type:'VR',status:'Simulated',trust:'Sandbox'}],agents:[{name:'Evan',role:'FOX Assistant',status:'Ready',enabled:true}],plugins:[],timeline:[],world:{objects:[{name:'Player Spawn',type:'Spawn',x:120,y:100},{name:'Forest Tree',type:'Environment',x:310,y:160},{name:'Test Vehicle',type:'Vehicle',x:510,y:230}]},studio:{entities:['VR Player','Interactable','Vehicle','AI Entity','Inventory','Trigger'],templates:['VR Starter','Horror Prototype','BONELAB Test Room']},logs:[]};
let state=load(); let view=state.view||'home', file=state.file||'Main.cs';
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null'); return merge(base,s||{});}catch{return structuredClone(base)}}
function merge(a,b){const o=structuredClone(a);for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&typeof o[k]==='object')o[k]=merge(o[k],b[k]);else o[k]=b[k]}return o}
function save(){state.view=view;state.file=file;localStorage.setItem(KEY,JSON.stringify(state));document.documentElement.style.setProperty('--accent',state.settings.accent||'#0796e6');document.documentElement.dataset.anim=state.settings.animations?'on':'off';document.documentElement.dataset.density=state.settings.density;document.body.classList.toggle('compact',state.settings.density==='compact');document.body.classList.toggle('rounded-none',!state.settings.rounded)}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>toastEl.classList.remove('show'),2300)}
function requirePerm(kind,action){if(state.permissions[kind])return true;toast(`Permission required: ${kind} • ${action}`);state.notifications.unshift({time:new Date().toLocaleString(),text:`Blocked ${action}: ${kind} permission not granted`});save();return false}
function grant(kind){state.permissions[kind]=true;state.notifications.unshift({time:new Date().toLocaleString(),text:`Permission granted: ${kind}`});save();toast(`${kind} permission granted`);render()}
function go(v){view=v;render()}
function setTitle(){const map={home:'Home',projects:'Projects',code:'Code',circuits:'Circuits',studio:'Game Studio',world:'World Builder',memory:'Memory Core',devices:'Device Bridge',permissions:'Permissions',agents:'Evan & Agents',tasks:'Task Board',timeline:'Timeline',plugins:'Tool Forge',sim:'Simulator',systems:'Systems',browser:'Browser',logs:'Build / Logs',docs:'Docs',settings:'Settings',about:'FOX OS'};T.textContent=map[view]||'FOX OS'}
function projectCount(){return Object.keys(state.project.files).length}
function render(){save();setTitle();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===view));let h='';switch(view){case'home':h=home();break;case'projects':h=projects();break;case'code':h=code();break;case'circuits':h=circuits();break;case'studio':h=studio();break;case'world':h=world();break;case'memory':h=memory();break;case'devices':h=devices();break;case'permissions':h=permissions();break;case'agents':h=agents();break;case'tasks':h=tasks();break;case'timeline':h=timeline();break;case'plugins':h=plugins();break;case'sim':h=simulator();break;case'systems':h=systems();break;case'browser':h=browser();break;case'logs':h=logs();break;case'docs':h=docs();break;case'settings':h=settings();break;case'about':h=about();break;default:h=home()}A.innerHTML=h;bind();}
function home(){const last=state.builds.at(-1), pending=state.tasks.filter(t=>!t.done).length;return `<div class="hero"><div><div class="eyebrow">FOX OS • v0.8</div><h1>Welcome back, ${esc(state.project.owner)}</h1><p class="muted">Your offline FOX ecosystem control center.</p></div><div class="hero-actions"><button class="primary" onclick="go('studio')">Open Game Studio</button><button onclick="go('memory')">Memory</button></div></div><div class="grid four stats"><div class="card"><b class="stat">${projectCount()}</b><span>Project files</span></div><div class="card"><b class="stat">${state.memory.length}</b><span>Memories</span></div><div class="card"><b class="stat">${pending}</b><span>Open tasks</span></div><div class="card"><b class="stat">${state.devices.filter(d=>d.status==='Online').length}</b><span>Online devices</span></div></div><div class="grid two"><div class="card"><div class="rowline"><h2>FOX Core</h2><span class="badge ok">ONLINE</span></div><div class="statuslist"><span>Memory Core <b>${state.memory.length} snapshots</b></span><span>Device Bridge <b>${state.devices.length} endpoints</b></span><span>Permission Core <b>${Object.values(state.permissions).filter(Boolean).length}/5 granted</b></span><span>Agent System <b>${state.agents.filter(a=>a.enabled).length} active</b></span></div></div><div class="card"><h2>Evan</h2><p class="muted">Your FOX assistant layer is ready.</p><p><span class="badge">Persistent context</span> <span class="badge">Project aware</span> <span class="badge">Offline tools</span></p><button onclick="go('agents')">Open agent space</button></div><div class="card"><h2>Continue building</h2><button onclick="go('world')">World Builder</button><button onclick="go('studio')">VR Game Studio</button><button onclick="go('plugins')">Tool Forge</button><button onclick="go('timeline')">Timeline</button></div><div class="card"><h2>Latest activity</h2><p class="muted">${state.history.length?esc(state.history[0]):'Nothing yet. Your workspace is ready.'}</p><p>${last?esc(last.result):'No builds recorded.'}</p><button onclick="go('logs')">Build Center</button></div></div>`}
function projects(){return `<div class="rowline"><div><h1>Projects</h1><p class="muted">Local workspaces with portable snapshots.</p></div><div><button onclick="newProject()">New</button><button onclick="importP()">Import</button><button onclick="exportP()">Export</button></div></div><div class="card" style="margin-top:14px"><div class="rowline"><div><h2>${esc(state.project.name)}</h2><p class="muted">${projectCount()} files • ${esc(state.project.target)} • v${esc(state.project.version)}</p></div><span class="badge ok">LOCAL</span></div><button class="primary" onclick="go('code')">Open workspace</button> <button onclick="snapshot('Project checkpoint')">Create snapshot</button> <button onclick="duplicateProject()">Duplicate</button></div><div class="grid two"><div class="card"><h2>Project manifest</h2><div class="setting"><span>Target</span><b>${esc(state.project.target)}</b></div><div class="setting"><span>Owner</span><b>${esc(state.project.owner)}</b></div><div class="setting"><span>Version</span><b>${esc(state.project.version)}</b></div></div><div class="card"><h2>Quick templates</h2><button onclick="insertTemplate('BoneLib')">BoneLib</button><button onclick="insertTemplate('WristHub')">WristHub</button><button onclick="insertTemplate('Event')">BONELAB Event</button></div></div>`}
function code(){const files=Object.keys(state.project.files);if(!state.project.files[file])file=files[0]||'Main.cs';return `<div class="split"><div class="files"><div class="filehead">FILES</div>${files.map(x=>`<button class="${x===file?'active':''}" onclick="sel('${esc(x)}')">${esc(x)}</button>`).join('')}<button onclick="addFile()">＋ New file</button><button onclick="deleteFile()">Delete selected</button></div><div class="editor"><div class="editorbar"><span>${esc(file)}</span><span><button onclick="formatCode()">Format</button><button onclick="saveCode()">Save</button></span></div><textarea id="ed" spellcheck="false">${esc(state.project.files[file]||'')}</textarea></div></div>`}
function circuits(){return `<div class="rowline"><div><h1>FOX Circuits</h1><p class="muted">Build logic visually. This version saves the canvas locally.</p></div><div><button onclick="addChip('Event')">+ Event</button><button onclick="addChip('Logic')">+ Logic</button><button onclick="addChip('Action')">+ Action</button><button class="primary" onclick="runCircuit()">Run</button></div></div><div id="circuit" class="circuit" style="margin-top:12px"><div class="chip" style="left:40px;top:45px">On Start</div><div class="chip" style="left:270px;top:145px">Check Input</div><div class="chip" style="left:500px;top:260px">Set Property</div></div><p class="tiny">Prototype canvas • future compiler target: FOX SDK / BONELAB integrations.</p>`}
function studio(){return `<div class="rowline"><div><h1>FOX Game Studio</h1><p class="muted">General-purpose VR creation workspace.</p></div><button class="primary" onclick="createGamePrototype()">Create prototype</button></div><div class="grid three studio-grid">${state.studio.entities.map(e=>`<div class="card toolcard"><b>${esc(e)}</b><p class="muted">Drop into a scene or expose as a visual-coder block.</p><button onclick="addStudioEntity('${esc(e)}')">Add</button></div>`).join('')}</div><div class="card"><h2>Game systems</h2><div class="chips">${['VR input','Hand tracking','Haptics','Inventory','Vehicles','AI','Day / Night','Save system','Audio zones','Interaction','Networking','Mod hooks'].map(x=>`<span class="badge">${x}</span>`).join(' ')}</div></div>`}
function world(){return `<div class="rowline"><div><h1>World Builder</h1><p class="muted">Schematic scene builder for VR prototypes.</p></div><div><button onclick="addWorld('Prop')">+ Prop</button><button onclick="addWorld('Trigger')">+ Trigger</button><button onclick="addWorld('Vehicle')">+ Vehicle</button></div></div><div class="world-preview card" style="margin-top:12px"><div class="world-grid"></div>${state.world.objects.map((o,i)=>`<div class="world-object" style="left:${o.x}px;top:${o.y}px" title="${esc(o.type)}">${esc(o.name)}</div>`).join('')}</div><div class="card" style="margin-top:12px"><h2>Scene objects</h2>${state.world.objects.map((o,i)=>`<div class="row"><span><b>${esc(o.name)}</b><br><span class="muted">${esc(o.type)}</span></span><button onclick="removeWorld(${i})">Remove</button></div>`).join('')}</div>`}
function memory(){return `<div class="rowline"><div><h1>Memory Core</h1><p class="muted">Persistent local context, snapshots, and notes.</p></div><div><button onclick="addMemory()">+ Memory</button><button onclick="snapshot('Manual memory snapshot')">Snapshot</button></div></div><div class="toolbar-card"><input id="memSearch" class="search" placeholder="Search memories..." oninput="filterMemory()"><select id="memTag" onchange="filterMemory()"><option value="">All tags</option><option>Project</option><option>Evan</option><option>World</option><option>Idea</option><option>System</option></select></div><div id="memoryList" class="list">${memoryRows()}</div>`}
function memoryRows(){const q=(document.getElementById('memSearch')?.value||'').toLowerCase(),tag=document.getElementById('memTag')?.value||'';const arr=state.memory.filter(m=>(!q||(m.title+' '+m.text).toLowerCase().includes(q))&&(!tag||m.tag===tag));return arr.length?arr.map((m,i)=>`<div class="row"><span><b>${esc(m.title)}</b><br><span class="muted">${esc(m.tag)} • ${esc(m.time)}</span><br>${esc(m.text)}</span><button onclick="deleteMemory(${state.memory.indexOf(m)})">Delete</button></div>`).join(''):'<div class="card muted">No matching memories.</div>'}
function devices(){return `<div class="rowline"><div><h1>Device Bridge</h1><p class="muted">Connect FOX clients when hardware is available; simulator works now.</p></div><button onclick="addDevice()">Pair device</button></div><div class="grid two">${state.devices.map((d,i)=>`<div class="card"><div class="rowline"><h2>${esc(d.name)}</h2><span class="badge ${d.status==='Online'?'ok':''}">${esc(d.status)}</span></div><p class="muted">${esc(d.type)} • ${esc(d.trust)}</p><button onclick="toggleDevice(${i})">${d.status==='Online'?'Disconnect':'Connect'}</button> <button onclick="removeDevice(${i})">Remove</button></div>`).join('')}</div><div class="card"><h2>Quest mode</h2><p class="muted">No headset required. The simulator provides a safe endpoint for testing pairing, permissions, and messages.</p><button onclick="simulateQuest()">Run Quest handshake</button></div>`}
function permissions(){const defs=[['memory','Memory Core'],['devices','Device Bridge'],['network','Network / Browser'],['files','Local file import / export'],['agents','Agent actions']];return `<div class="rowline"><div><h1>Permissions</h1><p class="muted">Strict-by-default. Every sensitive module starts blocked.</p></div><button onclick="revokeAll()">Revoke all</button></div><div class="list" style="margin-top:12px">${defs.map(([k,n])=>`<div class="row"><span><b>${n}</b><br><span class="muted">${state.permissions[k]?'Allowed':'Blocked'}</span></span><button onclick="${state.permissions[k]?`revoke('${k}')`:`grant('${k}')`}">${state.permissions[k]?'Revoke':'Allow'}</button></div>`).join('')}</div><div class="card" style="margin-top:12px"><h2>Testing override</h2><p class="muted">Temporary test mode expires when the page reloads.</p><button onclick="testMode()">Enable test mode</button></div>`}
function agents(){return `<div class="rowline"><div><h1>Evan & Agents</h1><p class="muted">Assistant identities with separate permissions and project context.</p></div><button onclick="addAgent()">+ Agent</button></div><div class="grid two" style="margin-top:12px">${state.agents.map((a,i)=>`<div class="card"><div class="rowline"><h2>${esc(a.name)}</h2><span class="badge ${a.enabled?'ok':''}">${a.enabled?'ACTIVE':'OFF'}</span></div><p>${esc(a.role)}</p><p class="muted">Can work with tasks, notes, code, and project context according to permissions.</p><button onclick="toggleAgent(${i})">${a.enabled?'Disable':'Enable'}</button><button onclick="agentNote(${i})">Give task</button></div>`).join('')}</div>`}
function tasks(){return `<div class="rowline"><div><h1>Task Board</h1><p class="muted">Turn ideas into small buildable steps.</p></div><button onclick="addTask()">+ Task</button></div><div class="list" style="margin-top:12px">${state.tasks.length?state.tasks.map((t,i)=>`<div class="row"><span><b class="${t.done?'done':''}">${esc(t.title)}</b><br><span class="muted">${esc(t.area)}</span></span><span><button onclick="toggleTask(${i})">${t.done?'Reopen':'Done'}</button><button onclick="deleteTask(${i})">×</button></span></div>`).join(''):'<div class="card muted">No tasks yet.</div>'}</div>`}
function timeline(){return `<div class="rowline"><div><h1>Timeline</h1><p class="muted">Checkpoint your FOX workspace before experiments.</p></div><button onclick="snapshot('Timeline checkpoint')">Create checkpoint</button></div><div class="list" style="margin-top:12px">${state.timeline.length?state.timeline.map((t,i)=>`<div class="row"><span><b>${esc(t.name)}</b><br><span class="muted">${esc(t.time)} • ${t.memoryCount} memories • ${t.fileCount} files</span></span><button onclick="restoreSnapshot(${i})">Restore</button></div>`).join(''):'<div class="card muted">No checkpoints yet.</div>'}</div>`}
function plugins(){return `<div class="rowline"><div><h1>Tool Forge</h1><p class="muted">Design modular FOX tools without rebuilding the core.</p></div><button onclick="addPlugin()">+ Tool</button></div><div class="grid two" style="margin-top:12px">${state.plugins.length?state.plugins.map((p,i)=>`<div class="card"><h2>${esc(p.name)}</h2><p class="muted">${esc(p.desc)}</p><span class="badge">${esc(p.type)}</span><button onclick="togglePlugin(${i})">${p.enabled?'Disable':'Enable'}</button></div>`).join(''):'<div class="card muted">No custom tools yet. Create one.</div>'}</div>`}
function simulator(){return `<h1>FOX Simulator</h1><p class="muted">Desktop simulation of FOX OS and future in-game clients.</p><div class="sim"><div class="simbar"><b>FOX OS</b><span class="badge ok">SIMULATED</span></div><div class="apps">${['Home','Code','Game Studio','World','Memory','Devices','Evan','Console'].map(x=>`<button onclick="simOpen('${x}')">${x}</button>`).join('')}</div><div class="appwindow" id="simWindow"><b>FOX OS Simulator</b><p class="muted">Safe local preview. No real headset required.</p></div></div>`}
function systems(){const rows=[['BoneLib','BONELAB core utilities','Integration slot'],['WristHub SDK','WristHub app integration','Integration slot'],['LabFusion','Multiplayer layer','Integration slot'],['MelonLoader / LemonLoader','Mod loading','Target'],['FOX Game SDK','Cross-game runtime','Planned'],['FOX Device SDK','Hardware capability bridge','Prototype']];return `<h1>Systems</h1><p class="muted">FOX integration registry.</p><table><thead><tr><th>System</th><th>Purpose</th><th>State</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td></tr>`).join('')}</tbody></table>`}
function browser(){return `<div class="browser"><div class="toolbar"><button onclick="browserBack()">←</button><button onclick="browserForward()">→</button><button onclick="reload()">↻</button><input id="url" class="url" value="https://github.com/foxbin8766-oss/FoxOSC"><button onclick="bookmark()">☆</button><button onclick="chrome()">Open</button><button class="primary" onclick="nav()">Go</button></div><iframe id="frame" class="frame" title="FOX Browser"></iframe></div>`}
function logs(){return `<div class="rowline"><div><h1>Build Center</h1><p class="muted">Offline validation and build records.</p></div><button class="primary" onclick="build()">Run validation build</button></div><div id="log" class="log" style="margin-top:12px">${esc(state.logs.join('\n'))||'FOX build center ready.'}</div><div class="list" style="margin-top:12px">${state.builds.map(b=>`<div class="row"><span><b>${esc(b.result)}</b><br><span class="muted">${esc(b.time)}</span></span><span class="badge">${esc(b.mode||'LOCAL')}</span></div>`).join('')}</div>`}
function docs(){return `<h1>FOX Docs</h1><div class="grid two"><div class="card"><h2>Architecture</h2><p class="muted">FOX Core → permissions → memory → devices → agents → creator tools.</p></div><div class="card"><h2>BONELAB</h2><p class="muted">BoneLib, WristHub SDK, LabFusion and loader integration are represented as explicit slots. No DLL compilation is claimed until a real toolchain is connected.</p></div><div class="card"><h2>Offline first</h2><p class="muted">Projects, memory, settings, tasks, world data and snapshots remain in local storage.</p></div><div class="card"><h2>Future bridge</h2><p class="muted">Quest and other devices can become clients through the Device SDK and game-specific adapters.</p></div></div>`}
function settings(){return `<h1>Settings</h1><div class="grid two"><div class="card"><h2>Appearance</h2><div class="setting"><span>Accent</span><input id="accent" type="color" value="${state.settings.accent}"></div><div class="setting"><span>Animations</span><input id="animations" type="checkbox" ${state.settings.animations?'checked':''}></div><div class="setting"><span>Rounded UI</span><input id="rounded" type="checkbox" ${state.settings.rounded?'checked':''}></div><div class="setting"><span>Density</span><select id="density"><option ${state.settings.density==='comfortable'?'selected':''}>comfortable</option><option ${state.settings.density==='compact'?'selected':''}>compact</option></select></div><div class="setting"><span>Wallpaper</span><select id="wallpaper"><option>grid</option><option>plain</option><option>dots</option></select></div><button class="primary" onclick="saveSettings()">Save appearance</button></div><div class="card"><h2>Data</h2><button onclick="exportAll()">Export FOX backup</button><button onclick="importAll()">Import FOX backup</button><button onclick="clearData()">Reset local data</button><p class="tiny">Backup contains local project, memory, tasks, permissions, settings, devices, agents, tools and snapshots.</p></div></div>`}
function about(){return `<div class="card"><div class="profile"><img class="avatar" src="fox-os-logo.png"><div><h1>FOX OS</h1><p class="muted">Chromebook Companion v0.8 • modular FOX ecosystem foundation</p></div></div><hr><p>This is the FOX OS developer companion for the BONELAB FOX ecosystem. It is not a standalone Android operating system.</p><p class="muted">Everything here is designed to be expandable into real device clients, game SDKs, creator tools and FOX integrations.</p></div>`}
function bind(){document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.v));const ed=document.getElementById('ed');if(ed)ed.addEventListener('input',()=>{state.project.files[file]=ed.value;save()});}
function sel(x){file=x;render()}function saveCode(){state.project.files[file]=document.getElementById('ed').value;save();toast('Code saved')}function formatCode(){const ed=document.getElementById('ed');ed.value=ed.value.replace(/[ \t]+$/gm,'');state.project.files[file]=ed.value;save();toast('Basic formatting applied')}
function newProject(){const n=prompt('Project name','My FOX VR Game');if(n){state.project={...structuredClone(defaults),name:n,files:{'Main.cs':'// FOX project entry point\n'}};file='Main.cs';state.history.unshift('Created project: '+n);save();go('code')}}
function renameProject(){const n=prompt('Project name',state.project.name);if(n){state.project.name=n;save();render()}}
function addFile(){const n=prompt('File name','App.cs');if(n&&!state.project.files[n]){state.project.files[n]='';file=n;save();render()}}
function deleteFile(){const files=Object.keys(state.project.files);if(files.length<=1){toast('Keep at least one file');return}if(confirm('Delete '+file+'?')){delete state.project.files[file];file=Object.keys(state.project.files)[0];save();render()}}
function duplicateProject(){state.project={...structuredClone(state.project),name:state.project.name+' Copy'};state.history.unshift('Duplicated project');save();render()}
function exportP(){const blob=new Blob([JSON.stringify(state.project,null,2)],{type:'application/json'});download(blob,(state.project.name||'foxos-project').replace(/[^a-z0-9_-]/gi,'_')+'.json')}
function importP(){if(!requirePerm('files','import project'))return;const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p.files)throw 0;state.project={...defaults,...p};file=Object.keys(state.project.files)[0];save();toast('Project imported');render()}catch{toast('Invalid FOX project')}};r.readAsText(f)};input.click()}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Export ready')}
function exportAll(){if(!requirePerm('files','export backup'))return;download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'FOXOS-backup-v0.8.json')}
function importAll(){if(!requirePerm('files','import backup'))return;const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=merge(base,JSON.parse(r.result));view='home';file=Object.keys(state.project.files)[0]||'Main.cs';save();render();toast('FOX backup restored')}catch{toast('Invalid backup')}};r.readAsText(f)};i.click()}
function saveSettings(){state.settings.accent=document.getElementById('accent').value;state.settings.animations=document.getElementById('animations').checked;state.settings.rounded=document.getElementById('rounded').checked;state.settings.density=document.getElementById('density').value;state.settings.wallpaper=document.getElementById('wallpaper').value;save();toast('Appearance saved');render()}
function clearData(){if(confirm('Reset all FOX OS local data?')){localStorage.removeItem(KEY);location.reload()}}
function build(){go('logs');const lines=['> FOX validation build','✓ Project loaded','✓ Source files found','✓ Project manifest valid','✓ Local FOX Core checks passed','✓ Permission registry valid','✓ Memory index valid','✓ Device bridge schema valid','✓ Game Studio schema valid','! Native DLL compilation remains an external toolchain step','✓ Offline validation complete.'];state.logs.push(...lines);state.builds.push({time:new Date().toLocaleString(),result:'Offline validation complete',mode:'LOCAL'});state.history.unshift('Validation build completed');save();render();toast('Validation complete')}
function addChip(kind){const c=document.getElementById('circuit');if(!c)return;const el=document.createElement('div');el.className='chip';el.textContent=kind;el.style.left=(40+Math.random()*480)+'px';el.style.top=(35+Math.random()*300)+'px';c.appendChild(el);enableChip(el);toast(kind+' chip added')}
function enableChip(el){if(el.dataset.bound)return;el.dataset.bound='1';el.onpointerdown=e=>{e.preventDefault();const r=el.parentElement.getBoundingClientRect(),ox=e.clientX-el.offsetLeft,oy=e.clientY-el.offsetTop;el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{el.style.left=Math.max(0,Math.min(r.width-el.offsetWidth,ev.clientX-r.left-ox))+'px';el.style.top=Math.max(0,Math.min(r.height-el.offsetHeight,ev.clientY-r.top-oy))+'px'};el.onpointerup=()=>el.onpointermove=null}}
function runCircuit(){state.history.unshift('Circuit executed');save();toast('Circuit executed in sandbox')}
function addStudioEntity(name){state.history.unshift('Added studio entity: '+name);toast(name+' added to prototype');}
function createGamePrototype(){state.project.name='FOX VR Prototype';state.project.target='FOX Game SDK';state.history.unshift('Created FOX VR prototype');save();go('studio');toast('VR prototype created')}
function addWorld(type){const n=prompt(type+' name',type+' '+(state.world.objects.length+1));if(!n)return;state.world.objects.push({name:n,type,x:50+Math.random()*550,y:40+Math.random()*230});save();render()}
function removeWorld(i){state.world.objects.splice(i,1);save();render()}
function addMemory(){if(!requirePerm('memory','create memory'))return;const title=prompt('Memory title','FOX idea');if(!title)return;const text=prompt('Memory','');state.memory.unshift({title,text:text||'',tag:'Idea',time:new Date().toLocaleString()});state.history.unshift('Memory created: '+title);save();render()}
function deleteMemory(i){if(!requirePerm('memory','delete memory'))return;if(confirm('Delete this memory?')){state.memory.splice(i,1);save();render()}}
function filterMemory(){const l=document.getElementById('memoryList');if(l)l.innerHTML=memoryRows()}
function snapshot(name){if(!requirePerm('memory','create snapshot'))return;state.timeline.unshift({name,time:new Date().toLocaleString(),memoryCount:state.memory.length,fileCount:projectCount(),data:structuredClone(state.project)});state.memory.unshift({title:name,text:'Workspace checkpoint',tag:'System',time:new Date().toLocaleString()});save();toast('Snapshot created');if(view==='timeline'||view==='memory')render()}
function restoreSnapshot(i){if(!requirePerm('memory','restore snapshot'))return;const t=state.timeline[i];if(!t)return;state.project=structuredClone(t.data);file=Object.keys(state.project.files)[0];state.history.unshift('Restored: '+t.name);save();go('code');toast('Snapshot restored')}
function addDevice(){if(!requirePerm('devices','pair device'))return;const n=prompt('Device name','FOX Device');if(!n)return;state.devices.push({name:n,type:'FOX Client',status:'Online',trust:'Paired'});save();render();toast('Device paired')}
function toggleDevice(i){if(!requirePerm('devices','change device state'))return;state.devices[i].status=state.devices[i].status==='Online'?'Offline':'Online';save();render()}
function removeDevice(i){if(!requirePerm('devices','remove device'))return;state.devices.splice(i,1);save();render()}
function simulateQuest(){if(!requirePerm('devices','Quest handshake'))return;state.history.unshift('Quest simulator handshake completed');state.notifications.unshift({time:new Date().toLocaleString(),text:'Quest simulator handshake successful'});save();toast('Quest handshake successful')}
function revoke(k){state.permissions[k]=false;save();render()}function revokeAll(){Object.keys(state.permissions).forEach(k=>state.permissions[k]=false);save();render();toast('All permissions revoked')}
function testMode(){Object.keys(state.permissions).forEach(k=>state.permissions[k]=true);state._testMode=true;toast('Temporary test mode enabled');render()}
function addAgent(){if(!requirePerm('agents','create agent'))return;const n=prompt('Agent name','New Agent');if(n){state.agents.push({name:n,role:'FOX Agent',status:'Ready',enabled:true});save();render()}}
function toggleAgent(i){if(!requirePerm('agents','control agent'))return;state.agents[i].enabled=!state.agents[i].enabled;save();render()}
function agentNote(i){if(!requirePerm('agents','assign agent task'))return;const t=prompt('Task for '+state.agents[i].name,'Explore a FOX idea');if(t){state.tasks.unshift({title:t,area:state.agents[i].name,done:false});state.history.unshift(state.agents[i].name+' received a task');save();toast('Task assigned')}}
function addTask(){const t=prompt('Task','Build something cool');if(t){state.tasks.unshift({title:t,area:'FOX',done:false});save();render()}}function toggleTask(i){state.tasks[i].done=!state.tasks[i].done;save();render()}function deleteTask(i){state.tasks.splice(i,1);save();render()}
function addPlugin(){const n=prompt('Tool name','My FOX Tool');if(!n)return;state.plugins.push({name:n,desc:'Custom modular FOX tool',type:'Local',enabled:true});save();render()}
function togglePlugin(i){state.plugins[i].enabled=!state.plugins[i].enabled;save();render()}
function simOpen(x){document.getElementById('simWindow').innerHTML=`<b>FOX ${esc(x)}</b><p class="muted">Simulated panel opened.</p><button onclick="toast('${esc(x)} action tested')">Test action</button>`}
function insertTemplate(type){const templates={BoneLib:'using BoneLib;\n\npublic void Start() {\n    // FOX startup\n}\n',WristHub:'// WristHub app template\npublic void InitializeApp() {\n    // FOX WristHub integration\n}\n',Event:'// BONELAB event handler\nvoid OnEvent() {\n    // Handle event\n}\n'};state.project.files[file]=(state.project.files[file]||'')+'\n'+templates[type];save();go('code');toast(type+' template inserted')}
function nav(){if(!requirePerm('network','browse web'))return;let u=document.getElementById('url').value.trim();if(!/^https?:\/\//i.test(u))u='https://www.google.com/search?q='+encodeURIComponent(u);document.getElementById('frame').src=u;document.getElementById('url').value=u;state.history.unshift('Browser: '+u);save()}
function reload(){const f=document.getElementById('frame');f.src=f.src}function chrome(){if(!requirePerm('network','open external browser'))return;window.open(document.getElementById('url').value,'_blank')}function bookmark(){const u=document.getElementById('url').value;if(u&&!state.bookmarks.includes(u)){state.bookmarks.push(u);save();toast('Bookmark saved')}}function browserBack(){try{document.getElementById('frame').contentWindow.history.back()}catch{}}function browserForward(){try{document.getElementById('frame').contentWindow.history.forward()}catch{}}
const commands=[['Go Home','home'],['Open Projects','projects'],['Open Code','code'],['Open Circuits','circuits'],['Open Game Studio','studio'],['Open World Builder','world'],['Open Memory Core','memory'],['Open Device Bridge','devices'],['Open Permissions','permissions'],['Open Evan','agents'],['Open Tasks','tasks'],['Open Timeline','timeline'],['Open Tool Forge','plugins'],['Launch Simulator','sim'],['Open Systems','systems'],['Open Browser','browser'],['Open Build Center','logs'],['Open Docs','docs'],['Open Settings','settings'],['New Project','new']];
function paletteOpen(){document.getElementById('palette').classList.remove('hidden');const i=document.getElementById('paletteInput');i.value='';paletteRender();i.focus()}let pi=0;function paletteRender(){const q=document.getElementById('paletteInput').value.toLowerCase(),list=commands.filter(x=>x[0].toLowerCase().includes(q));pi=Math.max(0,Math.min(pi,list.length-1));document.getElementById('paletteResults').innerHTML=list.map((x,i)=>`<div class="palette-item ${i===pi?'active':''}" data-cmd="${x[1]}">${x[0]}</div>`).join('');document.querySelectorAll('.palette-item').forEach(e=>e.onclick=()=>runCommand(e.dataset.cmd))}function runCommand(c){document.getElementById('palette').classList.add('hidden');if(c==='new')newProject();else go(c)}
document.getElementById('commandBtn').onclick=paletteOpen;document.getElementById('paletteInput').oninput=paletteRender;document.getElementById('palette').onclick=e=>{if(e.target.id==='palette')e.currentTarget.classList.add('hidden')};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();paletteOpen()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();toast('Workspace saved')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='b'){e.preventDefault();build()}if(e.key==='Escape')document.getElementById('palette').classList.add('hidden')});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window.deferredInstall=e;const b=document.getElementById('installBtn');if(b){b.hidden=false;b.onclick=async()=>{window.deferredInstall.prompt();await window.deferredInstall.userChoice;window.deferredInstall=null;b.hidden=true}}});window.addEventListener('appinstalled',()=>toast('FOX OS installed'));window.addEventListener('load',()=>{const b=document.getElementById('installBtn');if(b&&window.matchMedia('(display-mode: standalone)').matches)b.hidden=true});render();
